name: CICD
on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: setup py ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: install packages
      run: make install
    - name: lint
      run: make lint
    - name: test
      env:
        DATABRICKS_KEY: ${{ secrets.DATABRICKS_KEY }}
        SERVER_HOSTNAME: ${{ secrets.SERVER_HOSTNAME }}
        HTTP_PATH: ${{ secrets.HTTP_PATH }}
      run: make test
    - name: format
      run: make format